// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSb7O33ewIYKqEXTEifkK4c7RZhrZXliE',
    appId: '1:357665662689:web:81bd65ba14238d0a0c79a0',
    messagingSenderId: '357665662689',
    projectId: 'thevetapp-9b5be',
    authDomain: 'thevetapp-9b5be.firebaseapp.com',
    storageBucket: 'thevetapp-9b5be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMY23qZeyF3P069gaAdycHLLfFElOVswo',
    appId: '1:357665662689:android:95cc5aeb9cfe206d0c79a0',
    messagingSenderId: '357665662689',
    projectId: 'thevetapp-9b5be',
    storageBucket: 'thevetapp-9b5be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEoWJWXwMl8bpkf_XOn7xjPueWg-nPo9A',
    appId: '1:357665662689:ios:145403fe781e3d8a0c79a0',
    messagingSenderId: '357665662689',
    projectId: 'thevetapp-9b5be',
    storageBucket: 'thevetapp-9b5be.appspot.com',
    iosBundleId: 'com.example.vetapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEoWJWXwMl8bpkf_XOn7xjPueWg-nPo9A',
    appId: '1:357665662689:ios:982e5fd2413565cb0c79a0',
    messagingSenderId: '357665662689',
    projectId: 'thevetapp-9b5be',
    storageBucket: 'thevetapp-9b5be.appspot.com',
    iosBundleId: 'com.example.vetapp.RunnerTests',
  );
}
